### ISSUE TITLE
Is Chiron a viable alternative in order to map JSON into records?

### ISSUE THREAD

**Issue by mrange** [garethhubball/TwitchDeck#4]
See: https://neoeinstein.github.io/blog/2015/12-13-chiron-json-ducks-monads/index.html

Pros; gives more control to JSON objects with more than trivial semantics

Cons; more initial work.

**Comment by garethhubball** [comment]
Thank you for this - I'll have a look into it and see.

**Comment by garethhubball** [comment]
Closing as I believe that everything in master now uses Chiron. Thank you for the idea.
